# -*- coding: utf-8 -*-
"""modulo_2_exercicios_Samuel_Saturno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYvV901PyauJMApOQ0ATvucIADzZil9f

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo 02** | Python: Estruturas de Dados
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)
Aluno: Samuel Saturno
---

# **Tópicos**

<ol type="1">
  <li>Listas;</li>
  <li>Conjuntos;</li>
  <li>Dicionários.</li>
</ol>

---

# **Exercícios**

## 1\. Listas

Criei uma lista chamada `filmes` com o nome dos 10 primeiros filmes mais bem avaliados no site no [IMDB](https://www.imdb.com/chart/top/). Imprima o resultado.
"""

# Listas dos 10 melhores filmes classificados pelo IMDb.
filmes_IMDb = ['Um Sonho de Liberdade',
               'O Poderoso Chefão',
               'Batman: O Cavaleiro das Trevas',
               'O Poderoso Chefão II',
               '12 Homens e uma Sentença',
               'A Lista de Schindler',
               'O Senhor dos Anéis: O Retorno do Rei',
               'Pulp Fiction: Tempo de Violência',
               'O Senhor dos Anéis: A Sociedade do Anel',
               'Três Homens em Conflito'
]

print(filmes_IMDb)

"""Simule a movimentação do *ranking*. Utilize os métodos `insert` e `pop` para trocar a posição do primeiro e do segundo filme da lista. Imprima o resultado.


"""

# Modificandio a classificação do primeiro e segundo colocado
filmes_IMDb.insert(0,'O Poderoso Chefão' )
print(filmes_IMDb)

filmes_IMDb_new_classifier = filmes_IMDb.pop(2)
print(filmes_IMDb_new_classifier)

print(filmes_IMDb)

quantidade = len(filmes_IMDb)
print(quantidade)

"""---

## 2\. Conjuntos

Aconteceu um erro no seu *ranking*. Simule a duplicação dos três últimos filmes da lista. Imprima o resultado.
"""

# Lista dos dez melhores filmes com duplicatas em alguns itens.
filmes_IMDb_parte_2 = ['Um Sonho de Liberdade',
                       'O Poderoso Chefão',
                       'Batman: O Cavaleiro das Trevas',
                       'O Poderoso Chefão II',
                       '12 Homens e uma Sentença',
                       'A Lista de Schindler',
                       'O Senhor dos Anéis: O Retorno do Rei',
                       'Pulp Fiction: Tempo de Violência',
                       'Pulp Fiction: Tempo de Violência',
                       'O Senhor dos Anéis: A Sociedade do Anel',
                       'O Senhor dos Anéis: A Sociedade do Anel',
                       'Três Homens em Conflito',
                       'Três Homens em Conflito'
]

print(filmes_IMDb_parte_2)
type(filmes_IMDb_parte_2)

# Contagem dos itens da lista aponta 13 filmes ao invés de 10
quantidade_2 = len(filmes_IMDb_parte_2)
print(quantidade_2)

"""Utiliza a conversão `set` e `list` para remover os valores duplicados. Imprima o resultado."""

# Convertendo a lista para conjunto(set) para eliminar os itens em duplicata.
filmes_IMDb_parte_3 = set(filmes_IMDb_parte_2)
print(filmes_IMDb_parte_3)
type(filmes_IMDb_parte_3)

# Analisando a quantidade de itens do conjunto
quantidade_3 = len(filmes_IMDb_parte_3)
print(quantidade_3)

"""---

## 3\. Dicionários

Repita os exercícios da parte 1 (listas). Os elementos da lista `filmes` devem ser dicionários no seguinte formato: `{'nome': <nome-do-filme>, 'ano': <ano do filme>}, 'sinopse': <sinopse do filme>}`.
"""

filmes_IMDb_completo = {
                        'nome':'Um Sonho de Liberdade','ano': 1994, 'sinopse':'Andy Dufresne é condenado a duas prisões perpétuas consecutivas pelas mortes de sua esposa e de seu amante. Porém, só Andy sabe que ele não cometeu os crimes. No presídio, durante dezenove anos, ele faz amizade com Red, sofre as brutalidades da vida na cadeia, se adapta, ajuda os carcereiros, etc.',
                        'nome':'O Poderoso Chefão', 'ano': 1972, 'sinopse': 'Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios.',
                        'nome':'Batman: O Cavaleiro das Trevas','ano': 2008, 'sinopse':'Com a ajuda de Jim Gordon e Harvey Dent, Batman tem mantido a ordem na cidade de Gotham. Mas um jovem e anárquico criminoso, conhecido como Coringa, pretende testar o justiceiro e mergulhar a cidade em um verdadeiro caos.',
                        'nome':'O Poderoso Chefão II','ano': 1974, 'sinopse':'Depois da máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para os Estados Unidos. Lá, ele assassina Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poder de Vito cresce, mas sua família é o que mais importa para ele.',
                        'nome':'12 Homens e uma Sentença','ano': 1957, 'sinopse':'Seguindo o encerramento do caso do julgamento do assassinato cometido por um adolescente, os membros do júri devem chegar a um consenso sobre qual será o veredito. Enquanto os 12 indivíduos estão fechados em uma sala para tomar uma decisão, onze deles votam pela condenação do réu, porém um deles acredita na inocência do jovem e tenta convencer os outros a mudarem seus votos, dando início a um conflito que ameaça inviabilizar o delicado processo que vai decidir o destino do acusado.',
                        'nome':'A Lista de Schindler','ano': 1993, 'sinopse':'O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão.',
                        'nome':'O Senhor dos Anéis: O Retorno do Rei','ano': 2003, 'sinopse':'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência.',
                        'nome':'Pulp Fiction: Tempo de Violência','ano': 1994, 'sinopse':'Assassino que trabalha para a máfia se apaixona pela esposa de seu chefe quando é convidado a acompanhá-la, um boxeador descumpre sua promessa de perder uma luta e um casal tenta um assalto que rapidamente sai do controle.',
                        'nome':'O Senhor dos Anéis: A Sociedade do Anel','ano': 2001, 'sinopse':'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove seres que formam a Sociedade do Anel.',
                        'nome':'Três Homens em Conflito','ano':1966, 'sinopse':'Nos Estados Unidos, durante a Guerra de Secessão, um pistoleiro misterioso tenta trabalhar em conjunto com um bandido e um caçador de recompensas para encontrar um tesouro escondido. Os homens são obrigados a forjar uma difícil aliança visto que cada um conhece apenas uma parte da localização da fortuna. O problema é que nenhum deles tem a intenção de dividir a riqueza.'
}

print(filmes_IMDb_completo)
type(filmes_IMDb_completo)